- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters/status
  - poolers/status
  verbs:
  - get
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - backups/status
  - databases/status
  - scheduledbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - imagecatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters/finalizers
  - databases/finalizers
  - poolers/finalizers
  verbs:
  - update
