{{- /*

Copyright The CloudNativePG Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/ -}}

{{- /* Create Mutating Webhook */ -}}

{{- $should := include "cloudnative-pg.cluster.shouldWebhooks" . }}

{{- if eq $should "true" }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "cloudnative-pg.mutatingWebhookName" . }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.cluster.webhooks.certManagerCert }}
    cert-manager.io/inject-ca-from: "{{ $.Release.Namespace }}/{{ . }}"
    {{- end }}
  labels:
    {{- include "cloudnative-pg.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cloudnative-pg.serviceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-cnpg-io-v1-backup
      port: {{ .Values.operator.service.port }}
  failurePolicy: {{ .Values.cluster.webhooks.mutatingFailurePolicy }}
  name: mbackup.cnpg.io
  rules:
  - apiGroups:
    - postgresql.cnpg.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
  {{- if gt (len .Values.managedNamespaces) 0 }}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: "In"
        values: 
          {{- toYaml .Values.managedNamespaces | nindent 10 }}
  {{- end }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cloudnative-pg.serviceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-cnpg-io-v1-cluster
      port: {{ .Values.operator.service.port }}
  failurePolicy: {{ .Values.cluster.webhooks.mutatingFailurePolicy }}
  name: mcluster.cnpg.io
  rules:
  - apiGroups:
    - postgresql.cnpg.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
  {{- if gt (len .Values.managedNamespaces) 0 }}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: "In"
        values: 
          {{- toYaml .Values.managedNamespaces | nindent 10 }}
  {{- end }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cloudnative-pg.serviceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-cnpg-io-v1-scheduledbackup
      port: {{ .Values.operator.service.port }}
  failurePolicy: {{ .Values.cluster.webhooks.mutatingFailurePolicy }}
  name: mscheduledbackup.cnpg.io
  rules:
  - apiGroups:
    - postgresql.cnpg.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledbackups
  sideEffects: None
  {{- if gt (len .Values.managedNamespaces) 0 }}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: "In"
        values: 
          {{- toYaml .Values.managedNamespaces | nindent 10 }}
  {{- end }}
{{- end }}
