- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters/status
  verbs:
  - patch
  - update
